version: '3'

silent: false

vars:
  BIN_NAME: app
  BIN_PATH: /tmp/bin
  TARGET: '{{.BIN_PATH}}/{{.BIN_NAME}}'
  MAIN_PATH: ./

tasks:
  default:
    cmds:
      - task: list

  list:
    desc: List available tasks
    cmds:
      - go-task --list

  bootstrap:
    desc: Install commonly used tools on go projects
    cmds:
      - echo "fetching govulncheck..."
      - go get -tool golang.org/x/vuln/cmd/govulncheck
      - echo "fetching staticchec..."
      - go get -tool honnef.co/go/tools/cmd/staticcheck

  audit:
    desc: Tidy, Vet, Staticcheck and Vuln check
    deps:
      - tidy
      - test
    cmds:
      - go mod tidy -diff
      - go mod verify
      - test -z "$(shell gofmt -l .)"
      - go vet ./...
      - go tool staticcheck -checks=all,-ST1000,-U1000 ./...
      - go tool govulncheck ./...

  test:
    desc: Run test suite
    cmds:
      - go test -v -race -buildvcs ./...

  tidy:
    desc: Tidy .mod files and format .go files
    cmds:
      - go mod tidy -v
      - go fmt ./...

  build:
    desc: Build the application
    sources:
      - ./main.go
    generates:
      - "{{.BIN_PATH}}/{{.BIN_NAME}}"
    method: timestamp
    requires:
      vars: [TARGET, MAIN_PATH]
    cmds:
      - go build -o={{.TARGET}} {{.MAIN_PATH}}

  run:
    desc: Run the application
    deps:
      - build
    requires:
      vars: [TARGET]
    cmds:
      - "{{.TARGET}}"

  push:
    desc: Push changes to remote git repository
    cmds:
      - git push

  clean:
    desc: Remove build artifacts
    ignore_error: true
    cmds:
      - rm {{.TARGET}} 2> /dev/null
